"""Generate manuscript macros from the pinned CommonRoad reports."""

from __future__ import annotations

import json
from pathlib import Path
from statistics import median


ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "小论文-2" / "generated"


def _pct(value: float) -> str:
    return f"{100.0 * value:.1f}".rstrip("0").rstrip(".")


def generate() -> Path:
    reactive = json.loads(
        (GENERATED / "commonroad_reactive_results.json").read_text(encoding="utf-8")
    )
    adapter = json.loads(
        (GENERATED / "commonroad_batch_results.json").read_text(encoding="utf-8")
    )
    native = json.loads(
        (GENERATED / "commonroad_miku_native_results.json").read_text(encoding="utf-8")
    )
    reactive_rows = reactive["rows"]
    valid = sum(row.get("valid_solution") is True for row in reactive_rows)
    failures = sum(row.get("outcome") == "planner_failure" for row in reactive_rows)
    adapter_summary = {row["method"]: row for row in adapter["summary"]}
    lines = [
        "% Auto-generated by generate_commonroad_macros.py; do not edit.",
        f"\\newcommand{{\\CRReactiveScenarioCount}}{{{len(reactive_rows)}}}",
        f"\\newcommand{{\\CRReactiveValidCount}}{{{valid}}}",
        f"\\newcommand{{\\CRReactiveFailureCount}}{{{failures}}}",
        f"\\newcommand{{\\CRReactiveValidPct}}{{{_pct(valid / len(reactive_rows))}}}",
        f"\\newcommand{{\\CRAdapterCaseCount}}{{{adapter['scenario_count']}}}",
    ]
    native_rows = [row for row in native["rows"] if row.get("method") == "MIKU"]
    native_valid = sum(row.get("valid_solution") is True for row in native_rows)
    native_failures = sum(row.get("outcome") != "valid_solution" for row in native_rows)
    native_runtimes = [
        float(row["planner_runtime_ms"])
        for row in native_rows
        if row.get("planner_runtime_ms") is not None
    ]
    lines.extend(
        (
            f"\\newcommand{{\\CRNativeMikuScenarioCount}}{{{len(native_rows)}}}",
            f"\\newcommand{{\\CRNativeMikuValidCount}}{{{native_valid}}}",
            f"\\newcommand{{\\CRNativeMikuFailureCount}}{{{native_failures}}}",
            f"\\newcommand{{\\CRNativeMikuValidPct}}{{{_pct(native_valid / len(native_rows))}}}",
            f"\\newcommand{{\\CRNativeMikuMedianRuntime}}{{{median(native_runtimes):.2f}}}",
        )
    )
    for method, prefix in (("B0", "BZero"), ("MIKU", "Miku")):
        summary = adapter_summary[method]
        lines.extend(
            (
                f"\\newcommand{{\\CR{prefix}SuccessPct}}{{{_pct(summary['success_rate'])}}}",
                f"\\newcommand{{\\CR{prefix}CollisionPct}}{{{_pct(summary['collision_rate'])}}}",
                f"\\newcommand{{\\CR{prefix}MedianRuntime}}{{{summary['median_runtime_ms']:.2f}}}",
            )
        )
    output = GENERATED / "commonroad_macros.tex"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


if __name__ == "__main__":
    print(generate())
