"""Run paired component ablations for the complete MIKU method."""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import asdict, replace
from pathlib import Path

import numpy as np

from experiment_cases import CASE_KINDS, generate_case
from experiment_methods import MethodSpec, method_by_key, run_method
from experiment_metrics import (
    bootstrap_paired_difference,
    evaluate_run,
    exact_mcnemar,
)


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT / "小论文-2" / "generated"
FULL = method_by_key("MIKU")
ABLATIONS: tuple[MethodSpec, ...] = (
    replace(FULL, key="A1", label="w/o arrival projection", flags=replace(FULL.flags, tau_shift=False)),
    replace(FULL, key="A2", label="w/o longitudinal grouping", flags=replace(FULL.flags, grouping=False)),
    replace(FULL, key="A3", label="w/o Top-K spatial homotopy", flags=replace(FULL.flags, max_gap=False)),
    replace(FULL, key="A4", label="w/o threat-aware margin", flags=replace(FULL.flags, threat_delta=False)),
    replace(FULL, key="A5", label="w/o temporal homotopy graph", flags=replace(FULL.flags, corridor_inject=False)),
    replace(FULL, key="A6", label="w/o robust occupancy tube", flags=replace(FULL.flags, robust_prediction=False)),
    replace(FULL, key="A7", label="w/o alternating refinement", iterative=False, max_iterations=1, refine_on_demand=False),
    FULL,
)


def _write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=tuple(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def _aggregate(rows: list[dict]) -> list[dict]:
    output = []
    for case_kind in (*CASE_KINDS, "all"):
        for method in ABLATIONS:
            subset = [
                row
                for row in rows
                if row["method"] == method.key
                and (case_kind == "all" or row["case_kind"] == case_kind)
            ]
            runtime = np.asarray([row["runtime_ms"] for row in subset], dtype=float)
            output.append(
                {
                    "case_kind": case_kind,
                    "method": method.key,
                    "label": method.label,
                    "n": len(subset),
                    "success_rate": float(np.mean([row["success"] for row in subset])),
                    "collision_rate": float(np.mean([row["collision"] for row in subset])),
                    "progress_ratio_mean": float(
                        np.mean([row["progress_ratio"] for row in subset])
                    ),
                    "runtime_p95_ms": float(np.quantile(runtime, 0.95)),
                }
            )
    return output


def _paired(rows: list[dict]) -> list[dict]:
    indexed = {
        (row["case_kind"], row["seed"], row["method"]): row for row in rows
    }
    output = []
    bootstrap_seed = 97000
    for case_kind in (*CASE_KINDS, "all"):
        keys = sorted(
            {
                (row["case_kind"], row["seed"])
                for row in rows
                if case_kind == "all" or row["case_kind"] == case_kind
            }
        )
        for ablation in ABLATIONS[:-1]:
            for metric in ("success", "collision"):
                full = np.asarray(
                    [indexed[(*key, FULL.key)][metric] for key in keys], dtype=float
                )
                reduced = np.asarray(
                    [indexed[(*key, ablation.key)][metric] for key in keys], dtype=float
                )
                result = bootstrap_paired_difference(
                    full,
                    reduced,
                    seed=bootstrap_seed,
                )
                result.update(exact_mcnemar(full, reduced))
                bootstrap_seed += 1
                output.append(
                    {
                        "case_kind": case_kind,
                        "comparison": f"MIKU-{ablation.key}",
                        "metric": metric,
                        **result,
                    }
                )
    return output


def _macros(summary: list[dict], paired: list[dict]) -> str:
    method_words = {
        "A1": "AOne",
        "A2": "ATwo",
        "A3": "AThree",
        "A4": "AFour",
        "A5": "AFive",
        "A6": "ASix",
        "A7": "ASeven",
        "MIKU": "Miku",
    }
    overall = {row["method"]: row for row in summary if row["case_kind"] == "all"}
    lines = ["% Auto-generated by run_randomized_ablation.py; do not edit."]
    for method, row in overall.items():
        word = method_words[method]
        lines.extend(
            (
                f"\\newcommand{{\\Abl{word}SuccessPct}}{{{100*row['success_rate']:.1f}}}",
                f"\\newcommand{{\\Abl{word}CollisionPct}}{{{100*row['collision_rate']:.1f}}}",
                f"\\newcommand{{\\Abl{word}RuntimePninetyfive}}{{{row['runtime_p95_ms']:.2f}}}",
            )
        )
    for row in paired:
        if row["case_kind"] != "all":
            continue
        method = row["comparison"].split("-")[1]
        word = method_words[method]
        metric = "Success" if row["metric"] == "success" else "Collision"
        prefix = f"\\AblMikuVs{word}{metric}"
        lines.extend(
            (
                f"\\newcommand{{{prefix}Diff}}{{{100*row['mean_difference']:.1f}}}",
                f"\\newcommand{{{prefix}CiLow}}{{{100*row['ci_low']:.1f}}}",
                f"\\newcommand{{{prefix}CiHigh}}{{{100*row['ci_high']:.1f}}}",
                f"\\newcommand{{{prefix}McNemarP}}{{{row['mcnemar_exact_p']:.4g}}}",
            )
        )
    return "\n".join(lines) + "\n"


def run(seed_start: int, seed_count: int, output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    rows = []
    total = len(CASE_KINDS) * seed_count
    completed = 0
    for kind in CASE_KINDS:
        for seed in range(seed_start, seed_start + seed_count):
            case = generate_case(kind, seed)
            for method in ABLATIONS:
                rows.append(evaluate_run(run_method(method, case.planning_scenario), case))
            completed += 1
            if completed % 25 == 0 or completed == total:
                print(f"completed {completed}/{total} paired ablation cases", flush=True)

    summary = _aggregate(rows)
    paired = _paired(rows)
    _write_csv(output / "randomized_ablation_raw.csv", rows)
    _write_csv(output / "randomized_ablation_summary.csv", summary)
    _write_csv(output / "randomized_ablation_paired.csv", paired)
    (output / "randomized_ablation_macros.tex").write_text(
        _macros(summary, paired),
        encoding="utf-8",
    )
    metadata = {
        "protocol": "miku-randomized-ablation-v1",
        "seed_start": seed_start,
        "seed_count_per_kind": seed_count,
        "case_kinds": list(CASE_KINDS),
        "methods": [asdict(method) for method in ABLATIONS],
        "summary": summary,
        "paired_statistics": paired,
    }
    (output / "randomized_ablation_results.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed-start", type=int, default=0)
    parser.add_argument("--seeds", type=int, default=100)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if args.seed_start < 0 or args.seeds <= 0:
        parser.error("--seed-start must be non-negative and --seeds must be positive")
    run(args.seed_start, args.seeds, args.output)


if __name__ == "__main__":
    main()
